editURL = "https://github.com/BetterGUI-MC/Docs/edit/main/content/"
author.name = "HSGamer"
showVisitedLinks = true
disableSearchHiddenPages = true
disableSeoHiddenPages = true
disableTagHiddenPages = true
collapsibleMenu = true
disableInlineCopyToClipBoard = true
disableNextPrev = false
disableSwagger = true
disableLandingPageButton = true
themeVariant = [ "auto" ]
