editURL = "https://github.com/BetterGUI-MC/Docs/edit/main/content/"
description = "The Documentation for BetterGUI & its addons"
author = "HSGamer"
showVisitedLinks = true
disableSearchHiddenPages = true
disableSeoHiddenPages = true
disableTagHiddenPages = true
collapsibleMenu = true
disableInlineCopyToClipBoard = true
disableNextPrev = false
disableSwagger = true
disableMathJax = true
disableLandingPageButton = true
themeVariant = [ "auto" ]
